version: '3.8'

services:
  # Servicio para el servidor Nginx
  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    depends_on:
      - front
    networks:
      - app_network

  # Servicio para la aplicación Node.js y React
  front:
    build:
      context: ./front
    volumes:
      - ./front/src:/app/src
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
      - NODE_ENV=development
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
